export interface Config {
    drawOnPdf: boolean,
    selectionOnTop : boolean,
    autoAddAnki: boolean,
    deckName : string,
    addImageOption: boolean,
    addTextOption: boolean,
    addOcrTextOption: boolean,
    ocrLanguage: string,
    addTextAsHidden: boolean,
    singlePageMode: boolean,
    autoAddServer: boolean,
    showSelectionSizeOptions: boolean,
    autoDrawLines: boolean,
    autoAddAnnotationsToCard: boolean,
}